import * as fs from 'node:fs';
import * as path from 'node:path';
import { coordinate } from './artifacts.js';
import type { Loader } from './detect.js';

export interface InitScriptOptions {
  readonly minecraftVersion: string;
  readonly loader: Loader;
  readonly bridgeVersion: string;
  readonly port: number;
  readonly evalEnabled: boolean;
  readonly world: string | null;
  readonly username: string;
  readonly width: number;
  readonly height: number;
  readonly jdwpPort: number | null;
  /** Extra `-D` properties, exposed for tests and for `--gradle-args` style overrides. */
  readonly extraJvmArgs?: readonly string[];
}

function groovyString(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/**
 * Generates the init script the CLI injects at launch, so that a consumer repository never has to
 * be edited to be driveable (plan §4).
 *
 * The run task is configured through `JavaExec` rather than through Loom's or NeoGradle's own run
 * DSL: both plugins' `runClient` tasks are `JavaExec` subclasses, so one code path covers both
 * loaders and does not break when either plugin reshuffles its extensions.
 */
export function renderInitScript(options: InitScriptOptions): string {
  const dependency = coordinate(options.minecraftVersion, options.loader, options.bridgeVersion);

  const jvmArgs = [
    '-Dclientdevbridge.enabled=true',
    `-Dclientdevbridge.port=${options.port}`,
    ...(options.evalEnabled ? ['-Dclientdevbridge.eval=true'] : []),
    ...(options.jdwpPort === null
      ? []
      : [`-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=127.0.0.1:${options.jdwpPort}`]),
    ...(options.extraJvmArgs ?? []),
  ];

  const programArgs = [
    '--username',
    options.username,
    '--width',
    String(options.width),
    '--height',
    String(options.height),
    ...(options.world === null ? [] : ['--quickPlaySingleplayer', options.world]),
  ];

  return `// Generated by clientdevbridge-cli. Regenerated on every 'clientdevbridge start'; do not edit.
// It injects the ClientDevBridge mod into an unmodified consumer checkout and pins the
// determinism settings the screenshot comparisons depend on.

def clientDevBridgeDependency = ${groovyString(dependency)}
def clientDevBridgeJvmArgs = [
${jvmArgs.map((arg) => `        ${groovyString(arg)}`).join(',\n')}
]
def clientDevBridgeProgramArgs = [
${programArgs.map((arg) => `        ${groovyString(arg)}`).join(',\n')}
]

allprojects { project ->
    project.repositories {
        // mavenLocal first, so that a developer working on ClientDevBridge itself picks up
        // their own './gradlew publishToMavenLocal' build ahead of any released one.
        mavenLocal()
        maven {
            name = 'ClientDevBridge (CyclopsMC GitHub Packages)'
            url = 'https://maven.pkg.github.com/CyclopsMC/packages'
            credentials {
                username = project.findProperty('gpr.user') ?: System.getenv('MAVEN_USERNAME') ?: System.getenv('GITHUB_USER')
                password = project.findProperty('gpr.key') ?: System.getenv('MAVEN_KEY') ?: System.getenv('GITHUB_TOKEN')
            }
        }
    }

    // Loom remaps mods on the dev runtime classpath, so the Fabric build has to go through
    // its own configuration rather than a plain runtimeOnly.
    project.plugins.withId('fabric-loom') {
        project.dependencies.add('modLocalRuntime', clientDevBridgeDependency)
    }
    // NeoGradle and ModDevGradle discover mods from the runtime classpath directly.
    project.plugins.withId('net.neoforged.gradle.userdev') {
        project.dependencies.add('runtimeOnly', clientDevBridgeDependency)
    }
    project.plugins.withId('net.neoforged.moddev') {
        def configuration = project.configurations.findByName('additionalRuntimeClasspath')
        project.dependencies.add(configuration != null ? 'additionalRuntimeClasspath' : 'runtimeOnly', clientDevBridgeDependency)
    }

    project.tasks.matching { it.name == 'runClient' }.configureEach { task ->
        if (task instanceof JavaExec) {
            task.jvmArgs(clientDevBridgeJvmArgs)
            task.args(clientDevBridgeProgramArgs)
        } else {
            project.logger.warn("ClientDevBridge: task \${task.path} is not a JavaExec, so its JVM arguments were not set. " +
                    'Report this with the loader and plugin versions at https://github.com/CyclopsMC/clientdevbridge-cli/issues')
        }
    }
}
`;
}

/**
 * The client options that make screenshots reproducible from one run to the next.
 *
 * Anything that animates, adapts to the machine, or depends on focus is turned off; without this,
 * `compare` against a golden image is noise.
 */
export const DETERMINISM_OPTIONS: Readonly<Record<string, string>> = {
  guiScale: '2',
  pauseOnLostFocus: 'false',
  enableVsync: 'false',
  maxFps: '60',
  renderClouds: '"false"',
  particles: '2',
  ao: 'false',
  entityShadows: 'false',
  bobView: 'false',
  fov: '0.0',
  gamma: '0.0',
  darkMojangStudiosBackground: 'true',
  narrator: '0',
  soundCategory_master: '0.0',
  tutorialStep: 'none',
  skipMultiplayerWarning: 'true',
  onboardAccessibility: 'false',
  fullscreen: 'false',
};

export interface PinResult {
  readonly created: boolean;
  readonly changed: readonly string[];
}

/**
 * Writes the determinism options into the run directory's `options.txt`.
 *
 * Keys the caller did not ask about are preserved, so a hand-tuned dev options file survives.
 */
export function pinOptions(runDir: string): PinResult {
  const optionsFile = path.join(runDir, 'options.txt');
  fs.mkdirSync(runDir, { recursive: true });

  const existing = new Map<string, string>();
  const order: string[] = [];
  const created = !fs.existsSync(optionsFile);
  if (!created) {
    for (const line of fs.readFileSync(optionsFile, 'utf8').split('\n')) {
      const separator = line.indexOf(':');
      if (separator > 0) {
        const key = line.slice(0, separator);
        existing.set(key, line.slice(separator + 1));
        order.push(key);
      }
    }
  }

  const changed: string[] = [];
  for (const [key, value] of Object.entries(DETERMINISM_OPTIONS)) {
    if (existing.get(key) !== value) {
      if (existing.has(key)) {
        changed.push(key);
      } else {
        order.push(key);
      }
      existing.set(key, value);
    }
  }

  const rendered = order.map((key) => `${key}:${existing.get(key)}`).join('\n');
  fs.writeFileSync(optionsFile, `${rendered}\n`, 'utf8');
  return { created, changed };
}
