import * as fs from 'node:fs';
import * as path from 'node:path';
import { coordinate, GROOVY_DEPENDENCY, GROUP, releasesMavenUrl } from './artifacts.js';
import type { Loader } from './detect.js';

export interface InitScriptOptions {
  readonly minecraftVersion: string;
  readonly loader: Loader;
  readonly bridgeVersion: string;
  readonly port: number;
  readonly evalEnabled: boolean;
  readonly world: string | null;
  readonly username: string;
  readonly width: number;
  readonly height: number;
  readonly jdwpPort: number | null;
  /** The consumer project root, so the mod can resolve committed world templates. */
  readonly projectDir: string;
  /**
   * The Gradle path of the module whose client is being launched, e.g. `:loader-neoforge`, or an
   * empty string for a single-module project.
   */
  readonly targetProjectPath: string;
  /** Extra `-D` properties, exposed for tests and for `--gradle-args` style overrides. */
  readonly extraJvmArgs?: readonly string[];
}

function groovyString(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/**
 * Generates the init script the CLI injects at launch, so that a consumer repository never has to
 * be edited to be driveable (plan §4).
 *
 * The run task is configured through `JavaExec` rather than through Loom's or NeoGradle's own run
 * DSL: both plugins' `runClient` tasks are `JavaExec` subclasses, so one code path covers both
 * loaders and does not break when either plugin reshuffles its extensions.
 */
export function renderInitScript(options: InitScriptOptions): string {
  const dependency = coordinate(options.minecraftVersion, options.loader, options.bridgeVersion);

  const jvmArgs = [
    '-Dclientdevbridge.enabled=true',
    `-Dclientdevbridge.port=${options.port}`,
    `-Dclientdevbridge.projectDir=${options.projectDir}`,
    ...(options.evalEnabled ? ['-Dclientdevbridge.eval=true'] : []),
    ...(options.jdwpPort === null
      ? []
      : [`-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=127.0.0.1:${options.jdwpPort}`]),
    ...(options.extraJvmArgs ?? []),
  ];

  const programArgs = [
    '--username',
    options.username,
    '--width',
    String(options.width),
    '--height',
    String(options.height),
    ...(options.world === null ? [] : ['--quickPlaySingleplayer', options.world]),
  ];

  return `// Generated by clientdevbridge-cli. Regenerated on every 'clientdevbridge start'; do not edit.
// It injects the ClientDevBridge mod into an unmodified consumer checkout and pins the
// determinism settings the screenshot comparisons depend on.

def clientDevBridgeDependency = ${groovyString(dependency)}
// The eval escape hatch reaches Groovy through javax.script. It is added here rather than left to
// transitive resolution because the Cyclops publishing convention emits artifact-only POMs, so the
// published module carries no dependency metadata for a consumer to resolve.
def clientDevBridgeGroovy = ${groovyString(GROOVY_DEPENDENCY)}
// Only the module being launched is touched. A multiloader repo configures every loader module in
// the same build, and injecting into the ones that are not being run is at best pointless: on the
// Minecraft 26 toolchain, adding a dependency to Loom's project makes it set Minecraft up before
// its own mappings configuration is populated, which fails the whole build with an error that
// names neither this script nor the module it came from.
def clientDevBridgeTarget = ${groovyString(options.targetProjectPath)}
def clientDevBridgeJvmArgs = [
${jvmArgs.map((arg) => `        ${groovyString(arg)}`).join(',\n')}
]
def clientDevBridgeProgramArgs = [
${programArgs.map((arg) => `        ${groovyString(arg)}`).join(',\n')}
]

allprojects { project ->
    // Nothing at all is done to the modules that are not being launched. Adding even a repository
    // to Loom's project is enough to change how it resolves its own mappings.
    if (project.path != clientDevBridgeTarget) {
        return
    }

    // Both repositories are restricted to ClientDevBridge's own group. Adding an unfiltered
    // repository to somebody else's build is a real hazard -- mavenLocal in particular will shadow
    // any dependency a stale local build happens to have -- and this script has no business
    // affecting how the project resolves anything but the bridge.
    project.repositories {
        // mavenLocal first, so that a developer working on ClientDevBridge itself picks up
        // their own './gradlew publishToMavenLocal' build ahead of any released one.
        mavenLocal {
            content { includeGroup ${groovyString(GROUP)} }
        }
        maven {
            name = 'ClientDevBridge releases'
            // A static Maven repository served by GitHub Pages. No credentials block, and that is
            // the point: the CyclopsMC GitHub Packages Maven needs a token even for public
            // packages, so a consumer would have to set one up before they could launch a client.
            url = ${groovyString(releasesMavenUrl())}
            content { includeGroup ${groovyString(GROUP)} }
        }
    }

${
  options.loader === 'fabric'
    ? `    // Which configuration a runtime mod belongs in differs between Loom generations -- 1.15
    // dropped modLocalRuntime -- so the name is looked up rather than assumed. That keeps this
    // working across Minecraft versions without the CLI tracking each toolchain's configuration
    // names on top of everything else it already has to know.
    def firstExisting = { String... names ->
        for (String candidate : names) {
            if (project.configurations.findByName(candidate) != null) {
                return candidate
            }
        }
        return 'runtimeOnly'
    }
`
    : ''
}
    // Which loader this is comes from the CLI, which already had to decide before it could pick the
    // artifact to inject. Asking Gradle instead is not free: registering a
    // plugins.withId('net.fabricmc.fabric-loom') callback -- even an empty one -- is enough to make
    // Loom 1.15 set Minecraft up before the build script's dependencies { } block has run, and the
    // build dies with "Configuration 'mappings' has no dependencies", naming neither this script
    // nor what it did.
    //
    // The additions are deferred to afterEvaluate for a related reason: adding to a Loom-managed
    // configuration while the build script is still being evaluated has the same effect.
    project.afterEvaluate {
${
  options.loader === 'fabric'
    ? `        project.dependencies.add(firstExisting('modLocalRuntime', 'localRuntime', 'runtimeOnly'),
                clientDevBridgeDependency)
        // Groovy is a plain library, not a mod, so it must never go through Loom's remapping.
        project.dependencies.add('runtimeOnly', clientDevBridgeGroovy)`
    : `        // NeoGradle and ModDevGradle both discover mods from the runtime classpath directly,
        // and ModDevGradle 2 rejects additionalRuntimeClasspath outright, telling callers to
        // use a standard configuration instead.
        project.dependencies.add('runtimeOnly', clientDevBridgeDependency)
        project.dependencies.add('runtimeOnly', clientDevBridgeGroovy)`
}
    }

    project.tasks.matching { it.name == 'runClient' }.configureEach { task ->
        if (task instanceof JavaExec) {
            task.jvmArgs(clientDevBridgeJvmArgs)
            // Program arguments go through an argument provider rather than args(). Gradle emits
            // every static argument before every provider's, and ModDevGradle passes the real main
            // class through a provider -- so appending statically puts our first argument ahead of
            // it, and the launcher tries to load '--username' as the main class. Registering a
            // provider last keeps ours genuinely last.
            task.argumentProviders.add({ clientDevBridgeProgramArgs } as org.gradle.process.CommandLineArgumentProvider)
        } else {
            project.logger.warn("ClientDevBridge: task \${task.path} is not a JavaExec, so its JVM arguments were not set. " +
                    'Report this with the loader and plugin versions at https://github.com/CyclopsMC/clientdevbridge-cli/issues')
        }
    }
}
`;
}

/**
 * The client options that make screenshots reproducible from one run to the next.
 *
 * Anything that animates, adapts to the machine, or depends on focus is turned off; without this,
 * `compare` against a golden image is noise.
 */
export const DETERMINISM_OPTIONS: Readonly<Record<string, string>> = {
  guiScale: '2',
  pauseOnLostFocus: 'false',
  enableVsync: 'false',
  maxFps: '60',
  renderClouds: '"false"',
  particles: '2',
  ao: 'false',
  entityShadows: 'false',
  bobView: 'false',
  fov: '0.0',
  gamma: '0.0',
  darkMojangStudiosBackground: 'true',
  narrator: '0',
  soundCategory_master: '0.0',
  tutorialStep: 'none',
  skipMultiplayerWarning: 'true',
  onboardAccessibility: 'false',
  fullscreen: 'false',
};

export interface PinResult {
  readonly created: boolean;
  readonly changed: readonly string[];
}

/**
 * Writes the determinism options into the run directory's `options.txt`.
 *
 * Keys the caller did not ask about are preserved, so a hand-tuned dev options file survives.
 */
export function pinOptions(runDir: string): PinResult {
  const optionsFile = path.join(runDir, 'options.txt');
  fs.mkdirSync(runDir, { recursive: true });

  const existing = new Map<string, string>();
  const order: string[] = [];
  const created = !fs.existsSync(optionsFile);
  if (!created) {
    for (const line of fs.readFileSync(optionsFile, 'utf8').split('\n')) {
      const separator = line.indexOf(':');
      if (separator > 0) {
        const key = line.slice(0, separator);
        existing.set(key, line.slice(separator + 1));
        order.push(key);
      }
    }
  }

  const changed: string[] = [];
  for (const [key, value] of Object.entries(DETERMINISM_OPTIONS)) {
    if (existing.get(key) !== value) {
      if (existing.has(key)) {
        changed.push(key);
      } else {
        order.push(key);
      }
      existing.set(key, value);
    }
  }

  const rendered = order.map((key) => `${key}:${existing.get(key)}`).join('\n');
  fs.writeFileSync(optionsFile, `${rendered}\n`, 'utf8');
  return { created, changed };
}
